### ISSUE TITLE
Need to map a specific version identifier to a source

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-model#11]
The current code in linkml_model/linkml_files.py maps a version identifier (e.g. "v0.0.1") to the SHA associated with the version.  The SHA, however, doesn't give us the state of _any_ file at that point in time, just the files that have changed.  We need to add some code to linkml_files.py that allows us to go from:

`GITHUB_PATH_FOR(Source.META, Format.NATIVE_JSONLD, "v0.0.1")` to the version of `jsonld/meta.model.context.jsonld` at  the point that the version tag was added.

**Comment by sierra-moxon** [comment]
@hsolbrig - I'm closing this for now as stale, but please reopen if you think its still doable/higher priority? :)
