### ISSUE TITLE
Automate deployment of docs

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml-model#115]
As part of the migration to poetry, we switched off auto-deployment of docs

This should be brought back, see the old workflow:

https://github.com/linkml/linkml-model/blob/813d73abaf1271a6fddf22556270549bd33ac408/.github/workflows/main.yaml

__IMPORTANT__ check with @cmungall before merging any PR here. The way this site works is different from other schema sites

- we don't use gh-pages
- https://linkml.io/linkml-model/ serves up *everything* in the repo
- the w3id PURLs rely on this structure - don't break it

e.g.

```
wget -vvv https://w3id.org/linkml/meta.yaml
...
Location: https://linkml.github.io/linkml-model/linkml_model/model/schema/meta.yaml [following]
```

```
✗ wget -vvv https://w3id.org/linkml/meta.owl
...
Location: https://linkml.github.io/linkml-model/linkml_model/owl/meta.owl.ttl [following]
```

**Comment by sierra-moxon** [comment]
It looks like @sujaypatil96 added autodeploy of docs to the github actions in this PR: https://github.com/linkml/linkml-model/commit/fe5feb809a2c2cde1244dd3f1bbea4632d901bf4

I am closing for now, but please reopen if I  got this wrong.
