### ISSUE TITLE
Add testing for py37, py39, and py310

### ISSUE THREAD

**Issue by cthoyt** [linkml/linkml-model#49]
Right now the github actions are only running on py38. It's mixed together the code that runs testing and does commits, so I don't want to mess that up by sending a PR that adds all of these in a strategy. Maybe there's a tricky way to use the `if:` entry to only run the commit steps on py38

**Comment by sierra-moxon** [comment]
It looks like we've updated this since 2021, now we support tests on both 3.9 and 3.10, and we required 3.9 for this repository.  It would be nice to extend that support to 3.8, but I will make another ticket for that and close this one.
