### ISSUE TITLE
XML allows xsd:minInclusive and xsd:maxInclusive to apply to dates as well as numbers

### ISSUE THREAD

**Issue by ddooley** [linkml/linkml-model#53]
As per https://www.w3.org/TR/xmlschema-2/#dc-minInclusive.  In DataHarmonizer we allow minimum and maximum date ranges this way.

I was wondering if linkml:minimum_value and maximum_value could also be loosened to include date min max?
Currently linkml has:

    Description: for slots with ranges of type number, the value must be equal to or lowe than this
    Range: Integer

**Comment by cmungall** [comment]
This is a good suggestion.

I think we have to work through the implications of broadening the existing range, vs introducing new slots

**Comment by cmungall** [comment]
closing in favor of https://github.com/linkml/linkml/issues/751
