### ISSUE TITLE
what the heck is 11179 with respect to permissible value meanings?

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-model#59]

**Comment by turbomam** [comment]
Add documentation about [this](https://en.wikipedia.org/wiki/ISO/IEC_11179) to ???

**Comment by gaurav** [comment]
There might be some information about this (at least in the CCDH context) is at https://cancerdhc.github.io/terminology/ -- I believe @hsolbrig and @jiaola wrote this document.
