### ISSUE TITLE
Attach inlined metaslot to both 'slot definition' and 'slot expression'

### ISSUE THREAD

**Issue by deepakunni3** [linkml/linkml-model#90]
This ticket is related to the discussion here: https://github.com/linkml/linkml/issues/664

> "From it looks like indeed the inline metaslots were deliberately attached to slot_definition, but in future metamodel versions these become slot-expression slots, so they can be used in expressions as well as named slots"

We should change the domain of `inlined` metaslot such that `inlined` can be used in 'slot definition' as well as 'slot expression'.

**Comment by cmungall** [comment]
we may want to wait until it's include in linkml_runtime.linkml_model
